name: checkin_app

packages:
  - .
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  bootstrap:
    run: melos exec -- flutter pub get
    description: Instala dependências em todos os packages

  codegen:
    run: |
      melos exec --depends-on="build_runner" -- \
        dart run build_runner build --delete-conflicting-outputs
    description: Roda build_runner em todos os packages que o possuem

  analyze:
    run: melos exec -- dart analyze --fatal-infos
    description: Análise estática em todos os packages

  analyze:app:
    run: flutter analyze --fatal-warnings
    description: Análise estática no app principal

  test:
    run: melos exec --depends-on="test" -- dart test
    description: Testes unitários em todos os packages

  test:app:
    run: flutter test --coverage --reporter=expanded
    description: Testes do app principal com cobertura

  format:
    run: melos exec -- dart format .
    description: Formata código em todos os packages

  format:check:
    run: melos exec -- dart format --output=none --check .
    description: Verifica formatação em todos os packages
