// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6FTlc0bNgzATJ5qQWy5z6ojJqJhiL6Wc',
    appId: '1:44830797272:web:89438a163ca1b5720296ad',
    messagingSenderId: '44830797272',
    projectId: 'checkin-app-4bdd1',
    authDomain: 'checkin-app-4bdd1.firebaseapp.com',
    storageBucket: 'checkin-app-4bdd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMGa0ZHXToXU3kaO5RmuT2fdJG7WMoR4Y',
    appId: '1:44830797272:android:2840485b39ffd4bb0296ad',
    messagingSenderId: '44830797272',
    projectId: 'checkin-app-4bdd1',
    storageBucket: 'checkin-app-4bdd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbPgBgIBJpReybiyJXomVtDU29_aEHwR8',
    appId: '1:44830797272:ios:ddbc89a6815821000296ad',
    messagingSenderId: '44830797272',
    projectId: 'checkin-app-4bdd1',
    storageBucket: 'checkin-app-4bdd1.firebasestorage.app',
    iosBundleId: 'com.example.checkinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbPgBgIBJpReybiyJXomVtDU29_aEHwR8',
    appId: '1:44830797272:ios:ddbc89a6815821000296ad',
    messagingSenderId: '44830797272',
    projectId: 'checkin-app-4bdd1',
    storageBucket: 'checkin-app-4bdd1.firebasestorage.app',
    iosBundleId: 'com.example.checkinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6FTlc0bNgzATJ5qQWy5z6ojJqJhiL6Wc',
    appId: '1:44830797272:web:b863a96b52ab3dff0296ad',
    messagingSenderId: '44830797272',
    projectId: 'checkin-app-4bdd1',
    authDomain: 'checkin-app-4bdd1.firebaseapp.com',
    storageBucket: 'checkin-app-4bdd1.firebasestorage.app',
  );
}